/**
 * @file KospWindow_GraphicsConstantDefs.h
 *
 * @brief
 *
 * @date 2025-07-27
 *
 * @copyright KOSP Project 2025
 */

#ifndef H_KOSPWINDOW_GRAPHICSCONSTANTDEFS_H_
#define H_KOSPWINDOW_GRAPHICSCONSTANTDEFS_H_

#ifdef __cplusplus
extern "C" {
#endif

/* Generic colurs / colours of the x plane window bezel */
#define CAIRO_COLOUR_XPLANE_BLACK (0.0), (0.0), (0.0)
#define CAIRO_COLOUR_XPLANE_WHITE (1.0), (1.0), (1.0)
#define CAIRO_COLOUR_XPLANE_MENU_FRAME (0.282), (0.314), (0.342)

/* Colours of the menu and backgrounds. */
#define CAIRO_COLOUR_MENU_MARGIN (0.126), (0.150), (0.165)
#define CAIRO_COLOUR_MENU_BACKGROUND_SHADOW (0.029), (0.033), (0.037)
#define CAIRO_COLOUR_MENU_BACKGROUND (0.058), (0.067), (0.075)
#define CAIRO_COLOUR_MENU_BACKGROUND_GLOW (0.08), (0.102), (0.110)
#define CAIRO_COLOUR_MENU_BUTTON_BACKGROUND (0.134), (0.157), (0.173)
#define CAIRO_COLOUR_MENU_BUTTON_BACKGROUND_GLOW (0.181), (0.204), (0.224)

#define CAIRO_COLOUR_SLIDER_BAR_GREY (0.787), (0.796), (0.804)

/* Custom colour for slider bars. */
#define CAIRO_COLOUR_ON_OFF_SWITCH_GREEN (0.165), (0.479), (0.234)
#define CAIRO_COLOUR_ON_OFF_SWITCH_RED (0.750), (0.152), (0.163)

/* Properties of the vertical placement of the title bar */
#define KOSPWINDOW_TITLE_BIG_TEXT_Y (80)
#define KOSPWINDOW_TITLE_SMALL_TEXT_Y (105)

/* Properties of the vertical placement of the menu bar */
#define KOSPWINDOW_MENU_BAR_TOP_EDGE_Y (135)
#define KOSPWINDOW_MENU_BAR_TOP_EDGE_Y_GAPPED (138)
#define KOSPWINDOW_MENU_BAR_BOTTOM_EDGE_Y (190)

/* Properties of the background rounded rectangles */
#define KOSPWINDOW_MENU_ROUNDED_CORNER_OUTER_RADIUS (10)
#define KOSPWINDOW_MENU_ROUNDED_CORNER_INNER_RADIUS (3)
#define KOSPWINDOW_MENU_MARGIN_WIDTH (3)

/* Properties of a slider block */
#define KOSPWINDOW_SLIDER_START_X (50)
#define KOSPWINDOW_SLIDER_END_X (350)
#define KOSPWINDOW_SLIDER_START_Y (230)
#define KOSPWINDOW_SLIDER_END_Y (650)
#define KOSPWINDOW_SLIDER_TEXT_Y_OFFSET (20)
#define KOSPWINDOW_SLIDER_BAR_Y_OFFSET (45)
#define KOSPWINDOW_SLIDER_BAR_THICKNESS (4)

/* Vertical distance between each slider block */
#define KOSPWINDOW_SLIDER_Y_SPACING (85)

/* Slider Ball Parameters */
#define KOSPWINDOW_SLIDER_BALL_RADIUS (9)
#define KOSPWINDOW_SLIDER_BALL_INNER_RING_RADIUS (8)
#define KOSPWINDOW_SLIDER_BALL_SHADOW_SIZE (2)

/* Position of the Separator */
#define KOSPWINDOW_BOTTOM_SEPARATOR_Y (660)
#define KOSPWINDOW_BOTTOM_SEPARATOR_X_MARGIN (25)

/* Text at the bottom */
#define KOSPWINDOW_BOTTOM_TEXT_Y (720)

/* Anything more than this will be assumed to be invisible and therefore
 * clipped. */
#define KOSPWINDOW_SLIDER_MAX_NUM_DISPLAYABLE_SLIDERS (5)

#define KOSPWINDOW_SLIDER_DESCRIPTION_TEXT_SIZE (21)

/* How many empty sliders to show at the bottom of the page*/
#define KOSPWINDOW_SLIDER_BOTTOM_BUFFER_SPACE (1)

/* Speed of the smooth animation when you scroll down */
#define KOSPWINDOW_SLIDER_SCROLL_ANIM_SPEED (10)

/* How long the handle of the scroll bar is */
#define KOSPWINDOW_SLIDER_SCROLL_BAR_X (375)
#define KOSPWINDOW_SLIDER_SCROLL_BAR_START_Y (230)
#define KOSPWINDOW_SLIDER_SCROLL_BAR_END_Y (620)
#define KOSPWINDOW_SLIDER_SCROLL_BAR_LENGTH (150)

#define KOSPWINDOW_SLIDER_FADING_STRIP_THICKNESS (40)

#define KOSPWINDOW_MIXER_SLIDER_WIDTH (8)
#define KOSPWINDOW_MIXER_SLIDER_START_Y (270)
#define KOSPWINDOW_MIXER_SLIDER_END_Y (638)

#define KOSPWINDOW_MIXER_SMALL_MARKER_OFFSET_START_X (16)
#define KOSPWINDOW_MIXER_SMALL_MARKER_OFFSET_END_X (24)

#define KOSPWINDOW_MIXER_LABEL_TEXT_OFFSET_X (-50)
#define KOSPWINDOW_MIXER_LABEL_TEXT_OFFSET_Y (6)

#define KOSPWINDOW_MIXER_BIG_MARKER_OFFSET_START_X (13)
#define KOSPWINDOW_MIXER_BIG_MARKER_OFFSET_END_X (27)

#define KOSPWINDOW_MIXER_SURROUNDING_BOX_WIDTH (122)
#define KOSPWINDOW_MIXER_SURROUNDING_BOX_HEIGHT (472)
#define KOSPWINDOW_MIXER_SURROUNDING_BOX_VERTICAL_MARGIN (30)
#define KOSPWINDOW_MIXER_SURROUNDING_BOX_CORNER_RADIUS (10)
#define KOSPWINDOW_MIXER_SURROUNDING_BOX_START_Y (214)
#define KOSPWINDOW_MIXER_SURROUNDING_BOX_END_Y (735)

#define CAIRO_COLOUR_SLIDER_ACCENT_RED (0.60), (0.046), (0)
#define CAIRO_COLOUR_SLIDER_ACCENT_YELLOW (0.609), (0.549), (0.178)
#define CAIRO_COLOUR_SLIDER_ACCENT_GREEN (0.238), (0.460), (0.254)

#define CAIRO_COLOUR_MIXER_DESCRIPTION_TEXT_Y 705

#define CAIRO_COLOUR_X_DIST_BTWN_BARS (130)

#define KOSPWINDOW_MIXER_SLIDER_SWITCH_WIDTH (38)
#define KOSPWINDOW_MIXER_SLIDER_SWITCH_HEIGHT (76)
#define KOSPWINDOW_MIXER_SLIDER_SWITCH_CORNER_RADIUS (6)
#define KOSPWINDOW_MIXER_SLIDER_SWITCH_SOLID_RECTANGLE_FROM_EDGE (7)
#define KOSPWINDOW_MIXER_SLIDER_SWITCH_MIDDLE_LINE_THICKNESS (4)

#define CAIRO_COLOUR_MIXER_SLIDER_SWITCH_GREY1 (0.495), (0.518), (0.550)
#define CAIRO_COLOUR_MIXER_SLIDER_SWITCH_GREY2 (0.652), (0.679), (0.691)
#define CAIRO_COLOUR_MIXER_SLIDER_SWITCH_GREY3 (0.743), (0.765), (0.773)
#define CAIRO_COLOUR_MIXER_SLIDER_SWITCH_GREY4 (0.314), (0.338), (0.366)

/**
 * @brief Instance of the slider bar Y table.
 *        Refer to the header for description.
 *
 */
static const vect2_t numberYPosAndNumber[] = {
    {.x = -80, .y = 626},
    {.x = -60, .y = 611},
    {.x = -50, .y = 593},
    {.x = -40, .y = 575},
    {.x = -30, .y = 536},
    {.x = -20, .y = 498},
    {.x = -10, .y = 455},
    { .x = -5, .y = 419},
    {  .x = 0, .y = 370},
    {  .x = 5, .y = 322},
    { .x = 10, .y = 284},
    NULL_VECT2
};

static const vect2_t numberYPosAndNumberInv[] = {
    {.x = 284,  .y = 10},
    {.x = 322,   .y = 5},
    {.x = 370,   .y = 0},
    {.x = 419,  .y = -5},
    {.x = 455, .y = -10},
    {.x = 498, .y = -20},
    {.x = 536, .y = -30},
    {.x = 575, .y = -40},
    {.x = 593, .y = -50},
    {.x = 611, .y = -60},
    {.x = 626, .y = -80},
    NULL_VECT2
};

#define KOSPWINDOW_ON_OFF_SWITCH_START_Y (224)

#define KOSPWINDOW_ON_OFF_SWITCH_START_X (283)
#define KOSPWINDOW_ON_OFF_SWITCH_TEXT_START_X (28)
#define KOSPWINDOW_ON_OFF_SWITCH_Y_OFFSET (0)
#define KOSPWINDOW_ON_OFF_SWITCH_TEXT_Y_OFFSET (22)

#define KOSPWINDOW_ON_OFF_SWITCH_Y_SPACING (60)

#define KOSPWINDOW_ON_OFF_SWITCH_WIDTH (70)
#define KOSPWINDOW_ON_OFF_SWITCH_HEIGHT (32)
#define KOSPWINDOW_ON_OFF_SWITCH_CORNER_RADIUS (5)

#define KOSPWINDOW_ON_OFF_SWITCH_MAX_NUM_DISPLAYABLE_SWITCHS (8)
#define KOSPWINDOW_ON_OFF_SWITCH_BOTTOM_BUFFER_SPACE (1)

#define KOSPWINDOW_CHANGELOG_TITLE_SPACING_ABOVE (40)
#define KOSPWINDOW_CHANGELOG_TITLE_SPACING_BELOW (45)
#define KOSPWINDOW_CHANGELOG_LINE_SPACING (30)
#define KOSPWINDOW_CHANGELOG_TEXT_START_X (30)

#define KOSPWINDOW_CHANGELOG_SCROLL_BOTTOM_BUFFER_PX (-800)

#define KOSPWINDOW_CHANGELOG_SCROLL_PIXELS_PER_CLICK (150)

#ifdef __cplusplus
}
#endif
#endif /* H_KOSPWINDOW_GRAPHICSCONSTANTDEFS_H_ */
